% This script is intended to be a tool in aggregating and visualizing 
%   selected videos and folders.

% So I want as the input is the 
%   folder name, 
%   possibly the videos (probs not though), (could have an agg all flag)
%   Then the attrs I want aggregated over


tests = struct('attributes', {{{'False Positives','False Negatives','True Positives', 'True Negatives'}}}, ...
    'folders', {{'strel-disk7 thresh-0.08', 'strel-disk7 thresh-0.10', 'strel-disk7 thresh-0.12'}}, ...
    'folderRename', {{'Threshold = 0.08', 'Threshold = 0.10', 'Threshold = 0.12'}}, ...
    'plotTitle', 'Detections per Video Over Various Thresholds', ...
    'yAxisLabel', 'Occurences Per Frame', ...
    'saveLocation', 'DetectionVSThresh', ...
    'collapse', 1);


for testIndex = 1:size(tests,1)
    test = tests(testIndex);
    testaggregator(test.attributes, test.folders, test.folderRename, ...
        test.plotTitle, test.yAxisLabel, test.collapse, test.saveLocation)
end